#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

set -xe

. $(dirname $0)/pre_start_ruby-1.9
pushd ${OPENSHIFT_REPO_DIR} > /dev/null

# Run db:migrate
RACK_ENV=production bundle exec rake db:migrate

popd > /dev/null
